server:
  port: 5000
  servlet:
    context-path: /nft-change-service
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  application:
    name: nft-change-service
    admin:
        enabled: false
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      enabled: false
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    open-in-view: true
    hibernate:
      id:
        new_generator_mappings: false
      ddl-auto: update
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: thiagocms13@gmail.com
    password: udvbvqyfyiayrzfe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#jwt:
#  key:
#    private: classpath:app.key
#    public: classpath:app.pub
springdoc:
  version: 1.6.14
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
  openapi:
    info:
      title: truckDeliveryAPI
      version: 1.0